Numpy Performance

In [1]:
a=[1,2,3,4,5]
l = range(10000000)
%timeit [i**2 for i in l]

1.19 s ± 65.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
import numpy as np 
l = np.array(range(10000000))
%timeit l**2

38.2 ms ± 6.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
l=np.array(range(10))
l
l*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

Numpy Array

In [7]:
arr=np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr.ndim

1

In [7]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])  ## Square matrix
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2.shape

(3, 3)

In [9]:
arr2.ndim

2

In [10]:
arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr3.ndim
arr3.shape

(3, 4)

In [12]:
arr.shape  #It is tuple

NameError: name 'arr' is not defined

In [15]:
np.array(range(1,10,1.5) )  # only integer

TypeError: 'float' object cannot be interpreted as an integer

In [16]:
np.arange(1,10,.5)  # decimal

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [17]:
arr4=np.array([1,2.0,"subham"])  #every value will be converted into floating type
arr4

array(['1', '2.0', 'subham'], dtype='<U32')

#manually specify data types when creating Numpy array

In [18]:
arr5=np.array([1,2,3.0,4.5],dtype='float')
arr5

array([1. , 2. , 3. , 4.5])

In [34]:
arr5=np.array([1,2,3.0,4.5],dtype='str')
arr5

array(['1', '2', '3.0', '4.5'], dtype='<U3')

In [37]:
arr6=np.array([1,2,3.0,'a'],dtype='int')
arr6

ValueError: invalid literal for int() with base 10: 'a'

In [19]:
arr6=np.array([1,2,3.0,'2.5'],dtype='int')
arr6

ValueError: invalid literal for int() with base 10: '2.5'

#change type of array after creation

In [22]:
arr7=np.array([10,20,30])
arr8=arr7.astype('float')
arr8

array([10., 20., 30.])

#Indexing

In [46]:
m1=np.arange(10)  # 10 elements start with 0 index
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
m1[-2]

np.int64(8)

#Advanced indexing - 1-D array 

In [28]:
m1=np.array([100,200,300,400,500])
m1[[4]]

np.int64(500)

#Slicing is for continuous subpart os an array

In [30]:
m1=np.arange(10,20)
m1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
m1[:4]  # starts at 0 but ends at 3 - in slice start value is iclusive but end value is n-1 

array([10, 11, 12, 13])

In [33]:
m1[-5:-1] #start at -5 pos and goes till -1-1 (-2)

array([15, 16, 17, 18])

In [34]:
m1[-5:-1:-1]  # it will never reach to -1   ml[n,m]   n, n+1 ....m-1

array([], dtype=int64)

In [35]:
a=np.array([0,1,2,3,4,5])
a[4:] = 11
print(a)

[ 0  1  2  3 11 11]


#2D array

In [36]:
a=np.array(range(16))
print(a)
a.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


(16,)

In [61]:
a.ndim

1

In [ ]:
#reshape convert 1-D array to 2-D array. It creates a New array so original array does get change

In [62]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
a.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [66]:
a.reshape(1,16)   ## 1 2-D array OR  1 rows 16 cols

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [67]:
a.reshape(16,1)  ## 16 1-D array  OR  16 rows 1 col

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [68]:
a.reshape(8,-1)  #-1 indicates number of col is same as row

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [39]:
a.reshape(-1,4)   #-1 indicates number of rows is same as col

SyntaxError: invalid syntax (2227006506.py, line 1)

In [38]:
a.reshape(-1,-1)

SyntaxError: invalid syntax (3688866370.py, line 1)

In [72]:
np.arange(21,72,2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [42]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)]*= -1
print(x) 

[  5  -9  20  25   3  -5  16 -10  -8]


In [74]:
import numpy as np
a = np.arange(10)
print(a[2:5])

[2 3 4]


In [75]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

In [76]:
arr

array([10, 20, 30, 40, 50])

In [77]:
import numpy as np
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a.transpose()[-2,-2])

56
