In [1]:
#Vectorization - performing operations on entire array elements simultan
import numpy as np
a=np.array([10,12,14,16.17,18,20])

In [21]:
a

array([10.  , 12.  , 14.  , 16.17, 18.  , 20.  ])

In [4]:
#Let us perform element wise operation by squaring each element - we need to use any loop but we can directly use array

In [6]:
a**2

array([100.    , 144.    , 196.    , 261.4689, 324.    , 400.    ])

In [7]:
#Can we do the same for numpy function - if I want to apply Sin function for all these values let us try with 
np.sin(a)

array([-0.54402111, -0.53657292,  0.99060736, -0.4457722 , -0.75098725,
        0.91294525])

In [9]:
np.log(a) 
#All numpy function are optimized to do vector oprations

array([2.30258509, 2.48490665, 2.63905733, 2.78315767, 2.89037176,
       2.99573227])

In [10]:
#If we use normal function say Factorial from Math then if we pass entire arrary then we will get an error
import math
math.factorial(a)  #this gives error as a cannot be done means passing array , so we need to do iteratively

TypeError: only integer scalar arrays can be converted to a scalar index

In [11]:
#how to vectorize 
def new_ops(x):
    if x%2==0:
        return x**2
    else:
        return x**3
        

In [12]:
new_ops(1)

1

In [13]:
new_ops(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [15]:
#how to vectorize any function if it is not numpy
for i in a:
    print(new_ops(i))

100.0
144.0
196.0
4227.952113000001
324.0
400.0


In [18]:
vec_factorial = np.vectorize(math.factorial) # It will create Vectorized Function

In [19]:
vec_factorial(a)

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [22]:
vec_newops = np.vectorize(new_ops) # It will create Vectorized Function

In [23]:
vec_newops(a)

array([ 100.      ,  144.      ,  196.      , 4227.952113,  324.      ,
        400.      ])

In [24]:
#Element wise operation
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [28]:
b=np.arange(6,11)
b

array([ 6,  7,  8,  9, 10])

In [29]:
#It is possible to multiple a and b as they equal zised one-dimensional array
a*b

array([ 6, 14, 24, 36, 50])

In [30]:
d=np.arange(12).reshape(3,4)
e=np.arange(13,25).reshape(3,4)
print(d)
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [31]:
d*e

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

In [32]:
#For elementwise operation array must be of same size
#For example Matrix of 3x4 can be multiple to Matrix of 4x3 and that produces Matrix 3x3
#Matrix Multiplication can be done using 
# np.matmul(a,b)
# np.dot(a,b)
# a @ b --- from Python 3.5 version


In [34]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [35]:
b=np.arange(2,8).reshape(2,3)
b

array([[2, 3, 4],
       [5, 6, 7]])

In [36]:
np.matmul(a,b)

array([[12, 15, 18],
       [26, 33, 40]])

In [37]:
np.dot(a,b)

array([[12, 15, 18],
       [26, 33, 40]])

In [38]:
a@b

array([[12, 15, 18],
       [26, 33, 40]])

In [39]:
#homework
import numpy as np
import time

size = 10_000_000
a = np.arange(size)

# Python loop
start1 = time.time()
out1 = [x * 2 for x in a]
end1 = time.time()

# np.vectorize
def double(x): return x * 2
vec_func = np.vectorize(double)

start2 = time.time()
out2 = vec_func(a)
end2 = time.time()

# True NumPy vectorized
start3 = time.time()
out3 = a * 2
end3 = time.time()

print(f"Python loop:        {end1 - start1} seconds")
print(f"np.vectorize:       {end2 - start2} seconds")
print(f"True vectorized:    {end3 - start3} seconds")

Python loop:        1.2572836875915527 seconds
np.vectorize:       1.7216808795928955 seconds
True vectorized:    0.028475284576416016 seconds


In [40]:
#Shallow Copy and Deep Copy
l1=[1,2,3,4]
l2=l1  #l2 will be another view of l1 -- shallow copy

In [43]:
l1[0]=20

In [44]:
l2

[20, 2, 3, 4]

In [45]:
id(l1)

3181565204928

In [46]:
id(l2)

3181565204928

In [50]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [52]:
b=a+1  #Elemenwise operations - it assigns new memory location to b  - known as Deep Copy
b

array([2, 3, 4, 5])

c=a  # Another view of data
c

In [54]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [55]:
b=a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [56]:
a[0]=100
a

array([100,   2,   3,   4])

In [57]:
b

array([[100,   2],
       [  3,   4]])

In [58]:
np.shares_memory(a,b)

True

In [60]:
#To create Deep Copy we can use Numpy function
b=a.copy()

In [61]:
np.shares_memory(a,b)

False

In [62]:
c=a.view()

In [63]:
np.shares_memory(a,c)

True

In [66]:
#Exercide
a=np.array([1,2,3,4,5,6])
b=a[a%2==0]

In [67]:
np.shares_memory(a,b)

False

In [68]:
#Array Splitting - testing and training
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
np.split(a,3)  #Arrary splitting possible with equal division

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [71]:
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [74]:
np.split(a,[3,5,6])  #Unequal split with indices 

[array([10, 11, 12]), array([13, 14]), array([15]), array([16, 17, 18, 19])]

In [75]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
#Horizontal and Vertical direction  
np.split(a,2,axis=0)  # 2 equal sized array splitting by rows

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [77]:
np.split(a,2,axis=1) # 2 equal sized array splitting by columns  --- horizontal direction

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [78]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [79]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [81]:
#Stacking = opposite of splitting
#can be done np.stack(array1,srray2,axis=0) or vstack
#can be done np.stack(array1,srray2,axis=1) or hstack
a=np.arange(5)
a


array([0, 1, 2, 3, 4])

In [82]:
b=np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [84]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [85]:
np.hstack((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
c=np.hstack((a,b))

In [95]:
a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])