In [2]:
import numpy as np
a=np.arange(1,13)
a.ndim

1

In [3]:
a.shape

(12,)

In [4]:
len(a)

12

In [ ]:
a.reshape(4,4) #invalid operation as there 12 element but reshape expects 16 elements

In [8]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
a.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
b=a.reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
b.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [13]:
b.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Transpose can create a new array and works similar way for numeric and alphanumric data

In [14]:
#indexing and slicing in 2D Array

In [18]:
m1=np.arange(1,10).reshape(3,3)
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

index helps to extract elements faster - index start from 0

In [19]:
m1[2][0]

np.int64(7)

We can pass multiple indicess wto  2 D array

In [22]:
m1[[0,1,2],[0,1,2]]

array([1, 5, 9])

In [23]:
m1[[0,1],[0,1]]

array([1, 5])

In [24]:
#slicing -- 2 rows will be extracted from index 0 and 1
m1[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
m1[:]    # all rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
#only first 2 columns 
m1[:3,:2]   # OR m1[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [31]:
m1[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [37]:
m2=np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
m2[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [39]:
m2[0:3,1:4:2]  # to jump to column 4 after 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [41]:
m2[:,[1,2,3]]   # all rows but column at 1,2 and 3

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [42]:
a=[1,2,3,4,5]
b=[8,7,6]
a[3:]=b[::-2]
print(a)

[1, 2, 3, 6, 8]


In [43]:
np.sum(m1)

np.int64(45)

In [44]:
np.min(m1)   #minimum value od array

np.int64(1)

In [45]:
np.max(m2)  #maximum value od array

np.int64(12)

In [47]:
#Lowest stock per day - we need to give Axis information  --- to define row and column
np.min(m1,axis=1)

array([1, 4, 7])

In [ ]:
np.min?

In [50]:
#Average across all cells
np.mean(m2)

np.float64(6.5)

In [51]:
np.mean(m2,axis=0)  #column wise Average - horizontal direction

array([5., 6., 7., 8.])

In [52]:
np.mean(m2,axis=1)  #row wise Average -- vertical direction

array([ 2.5,  6.5, 10.5])

In [54]:
m3=m2[:,[0,1]]
np.mean(m3,axis=0)

array([5., 6.])

In [55]:
#Sale on ecommerce
prices = np.array([50,45,25,30,35])
#budget 
bdg=35
prices <= bdg  # will return array 

array([False, False,  True,  True,  True])

In [56]:
prices > bdg

array([ True,  True, False, False, False])

In [57]:
np.any(prices<=bdg)  # at least one (1) true 

np.True_

In [58]:
np.all(prices<=bdg)

np.False_

In [59]:
prices=np.array([45,55,60,75,40,90]) #This is product pricess let us give discount for prices > 50 
np.where(prices > 50, prices *.9, prices)

array([45. , 49.5, 54. , 67.5, 40. , 81. ])

In [63]:
#BP Array have readings of BP of the patients
#If bp > 140 then we want to say that patient is at higher risk
bp=np.array([120, 150, 135, 160, 175])
np.where(bp > 140,'High','Normal')

array(['Normal', 'High', 'Normal', 'High', 'High'], dtype='<U6')

In [66]:
a=np.array([9,3,2,5,7,1,6])  # Sorting changes the object - sort method 
a.sort()
a

array([1, 2, 3, 5, 6, 7, 9])

In [67]:
a=np.array([9,3,2,5,7,1,6])  # Sort() from np  
np.sort(a)

array([1, 2, 3, 5, 6, 7, 9])

In [68]:
a

array([9, 3, 2, 5, 7, 1, 6])

In [69]:
np.sort(a)

array([1, 2, 3, 5, 6, 7, 9])

In [70]:
b=np.sort(a)

In [71]:
b[::-1]   #reversing b 

array([9, 7, 6, 5, 3, 2, 1])

In [73]:
a2=np.array([[6,2,3],[8,9,1],[8,2,1]])
a2

array([[6, 2, 3],
       [8, 9, 1],
       [8, 2, 1]])

In [74]:
np.sort(a2)   # sort at horizontal direction  same as np.sort(a2,axis=1) 

array([[2, 3, 6],
       [1, 8, 9],
       [1, 2, 8]])

In [75]:
np.sort(a2,axis=0) #sort at vertical 

array([[6, 2, 1],
       [8, 2, 1],
       [8, 9, 3]])

In [82]:
#Full sorting of array - 
# need to first convert into 1-D Format 
# sort the 1-D array
# again to convert into 2-D
a2.flatten()  # Convert 2-D to 1-D
np.sort(a2.flatten()).reshape(3,3)

array([[1, 1, 2],
       [2, 3, 6],
       [8, 8, 9]])

#Vectoriztion refers to performing operations on entire arrays or array elements simultaneouly, which is significantly faster and 
more efficient than using loop
Numpy does vectorization which is its inherent feature

In [84]:
#'condition' implies the situation that arr has at least one value smaller than or equal to 0.6. Which option is true with respect to the code and condition?
arr = 2 * np.arange(0,2,0.5)
if arr <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy") 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [86]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [87]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [88]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

In [89]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [90]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [91]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [1]:
np.vectorize/?

SyntaxError: invalid syntax (557039793.py, line 1)

In [5]:
import numpy as np


def extract_subarray(arr):
    '''
    INPUT: arr -> 2D array
        OUPUT: result -> 2D array
    '''
    ### STEP1: Get the rows (2nd  to 4th row)
    
    row_array = arr[[2,4],[:-3]
    
    
    #### STEP 2: Get the last 3 cols from the row array
    
    #cols_array = ______
    
    #### STEP3: Reverse the rows in cols array
    
    result = ________
    

    return result

SyntaxError: invalid syntax (1947980488.py, line 13)

In [48]:
import numpy as np
arr=np.array([[ 0,  1,  2,  3],  
 [ 4,  5,  6,  7],   
 [ 8,  9, 10, 11],   
 [12, 13, 14, 15],   
 [16, 17, 18, 19]])
row_array =  arr[1:4, -3:]
col_array = row_array[::][::-1]
#extract_subarray(arr)
col_array

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

In [33]:
 arr[1:4, -3:][::-1]

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

In [57]:
#Mean age of bird crane
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])

In [64]:
crane_ages=age[birds=='Cranes']

In [67]:
np.round(np.mean(crane_ages),2)

np.float64(4.75)

In [68]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [77]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print( v[:,])
#print((x / v[:,None]))

[200 300 400]


In [70]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

21


In [4]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a)  #.reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [5]:
x

array([[16, 81, 33],
       [ 5,  6,  1]])

In [6]:
x.reshape(2,3)

array([[16, 81, 33],
       [ 5,  6,  1]])

In [3]:
a

array([[16,  5],
       [81,  6],
       [33,  1]])